development:
  adapter: sqlite3
  database: autumns_play_date_production
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: autumns_play_date_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: autumns_play_date_production
  pool: 5
  timeout: 5000